development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

production:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

test:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123089e0u9fwewefkhjwefewf456789"

